<?php

namespace Fintech\MetaData\Seeders;

use Fintech\Core\Enums\MetaData\CatalogType;
use Fintech\MetaData\Facades\MetaData;
use Illuminate\Database\Seeder;

class IdDocTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach ($this->data() as $entry) {
            $entry['type'] = CatalogType::IdentityDocument->value;
            $entry['enabled'] = false;
            MetaData::idDocType()->create($entry);
        }
    }

    private function data(): array
    {
        return array(
            array(
                'name' => 'Passport',
                'code' => 'passport',
                'vendor_code' => array(
                    'remit' =>
                        array(
                            'argani' => null,
                            'city_bank' => null,
                            'emq_api' => null,
                            'trans_fast' => 'passport',
                            'valyou' => null,
                            'islami_bank' => null,
                        ),
                    'ekyc' =>
                        array(
                            'shufti_pro' => 'passport',
                            'signzy' => null,
                            'onfido' => 'passport',
                        ),
                ),
                'catalog_data' => array(
                    'sides' => '1',
                ),
                'countries' => array(
                    1, 11, 15, 17, 18, 25, 32, 36, 44, 56, 79, 96, 99, 100, 109, 101, 102, 104, 107, 108, 112, 113, 114, 115, 116, 118, 129, 146, 130, 142, 149, 161, 162, 164, 169, 174, 187, 192, 200, 207, 208, 209, 211, 212, 219, 224, 229, 232, 237, 19,),
            ),
            array(
                'name' => 'Driving Licence',
                'code' => 'driving-licence',
                'vendor_code' => array(
                    'remit' =>
                        array(
                            'argani' => null,
                            'city_bank' => null,
                            'emq_api' => null,
                            'trans_fast' => 'driving_license',
                            'valyou' => null,
                            'islami_bank' => null,
                        ),
                    'ekyc' =>
                        array(
                            'shufti_pro' => 'driving_license',
                            'signzy' => null,
                            'onfido' => 'driving_licence',
                        ),
                ),
                'catalog_data' => array(
                    'sides' => '1',
                ),
                'countries' => array(
                    11, 15, 18, 32, 44, 56, 79, 96, 100, 104, 107, 108, 113, 114, 129, 142, 161, 162, 169, 174, 187, 192, 200, 208, 211, 224, 232, 237, 19,),
            ),
            array(
                'name' => 'National Identity Card',
                'code' => 'national-identity-card',
                'vendor_code' => array(
                    'remit' =>
                        array(
                            'argani' => null,
                            'city_bank' => null,
                            'emq_api' => null,
                            'trans_fast' => 'id_card',
                            'valyou' => null,
                            'islami_bank' => null,
                        ),
                    'ekyc' =>
                        array(
                            'shufti_pro' => 'id_card',
                            'signzy' => null,
                            'onfido' => 'national_identity_card',
                        ),
                ),
                'catalog_data' => array(
                    'sides' => '2',
                ),
                'countries' => array(
                    15, 17, 18, 32, 44, 56, 79, 96, 99, 100, 107, 108, 113, 114, 129, 161, 162, 169, 174, 192, 208, 211, 224, 232, 19,),
            ),
            array(
                'name' => 'Residence Permit',
                'code' => 'residence-permit',
                'vendor_code' => array(
                    'remit' =>
                        array(
                            'argani' => null,
                            'city_bank' => null,
                            'emq_api' => null,
                            'trans_fast' => 'residence_permit',
                            'valyou' => null,
                            'islami_bank' => null,
                        ),
                    'ekyc' =>
                        array(
                            'shufti_pro' => 'residence_permit',
                            'signzy' => null,
                            'onfido' => 'residence_permit',
                        ),
                ),
                'catalog_data' => array(
                    'sides' => '2',
                ),
                'countries' => array(
                    56, 107, 129, 161, 174, 187, 208, 224,),
            ),
            array(
                'name' => 'Voter Id',
                'code' => 'voter-id',
                'vendor_code' => array(
                    'remit' =>
                        array(
                            'argani' => null,
                            'city_bank' => null,
                            'emq_api' => null,
                            'trans_fast' => 'voter_id',
                            'valyou' => null,
                            'islami_bank' => null,
                        ),
                    'ekyc' =>
                        array(
                            'shufti_pro' => 'voter_id',
                            'signzy' => null,
                            'onfido' => 'voter_id',
                        ),
                ),
                'catalog_data' => array(
                    'sides' => '1',
                ),
                'countries' => array(
                    99, 169,),
            ),
            array(
                'name' => 'Tax Id',
                'code' => 'tax-id',
                'vendor_code' => array(
                    'remit' =>
                        array(
                            'argani' => null,
                            'city_bank' => null,
                            'emq_api' => null,
                            'trans_fast' => 'tax_id',
                            'valyou' => null,
                            'islami_bank' => null,
                        ),
                    'ekyc' =>
                        array(
                            'shufti_pro' => 'tax_id',
                            'signzy' => null,
                            'onfido' => 'tax_id',
                        ),
                ),
                'catalog_data' => array(
                    'sides' => '1',
                ),
                'countries' => array(
                    99,),
            ),
            array(
                'name' => 'Social Security Card',
                'code' => 'social-security-card',
                'vendor_code' => array(
                    'remit' =>
                        array(
                            'argani' => null,
                            'city_bank' => null,
                            'emq_api' => null,
                            'trans_fast' => 'social_security_card',
                            'valyou' => null,
                            'islami_bank' => null,
                        ),
                    'ekyc' =>
                        array(
                            'shufti_pro' => 'social_security_card',
                            'signzy' => null,
                            'onfido' => 'social_security_card',
                        ),
                ),
                'catalog_data' => array(
                    'sides' => '1',
                ),
                'countries' => array(
                    107, 169,),
            ),
            array(
                'name' => 'Postal Identity Card',
                'code' => 'postal-identity-card',
                'vendor_code' => array(
                    'remit' =>
                        array(
                            'argani' => null,
                            'city_bank' => null,
                            'emq_api' => null,
                            'trans_fast' => 'postal_identity_card',
                            'valyou' => null,
                            'islami_bank' => null,
                        ),
                    'ekyc' =>
                        array(
                            'shufti_pro' => 'postal_identity_card',
                            'signzy' => null,
                            'onfido' => 'postal_identity_card',
                        ),
                ),
                'catalog_data' => array(
                    'sides' => '1',
                ),
                'countries' => array(
                    107, 169,),
            ),
            array(
                'name' => 'Professional Qualification Card',
                'code' => 'professional-qualification-card',
                'vendor_code' => array(
                    'remit' =>
                        array(
                            'argani' => null,
                            'city_bank' => null,
                            'emq_api' => null,
                            'trans_fast' => 'professional_qualification_card',
                            'valyou' => null,
                            'islami_bank' => null,
                        ),
                    'ekyc' =>
                        array(
                            'shufti_pro' => 'professional_qualification_card',
                            'signzy' => null,
                            'onfido' => 'professional_qualification_card',
                        ),
                ),
                'catalog_data' => array(
                    'sides' => '1',
                ),
                'countries' => array(
                    169,),
            ),
            array(
                'name' => 'Work Permit',
                'code' => 'work-permit',
                'vendor_code' => array(
                    'remit' =>
                        array(
                            'argani' => null,
                            'city_bank' => null,
                            'emq_api' => null,
                            'trans_fast' => 'work_permit',
                            'valyou' => null,
                            'islami_bank' => null,
                        ),
                    'ekyc' =>
                        array(
                            'shufti_pro' => 'work_permit',
                            'signzy' => null,
                            'onfido' => 'work_permit',
                        ),
                ),
                'catalog_data' => array(
                    'sides' => '2',
                ),
                'countries' => array(
                    192,),
            ),
        );
    }

//    private function data_old()
//    {
//        return array(
//            array(
//                'id' => 1,
//                'country_id' => 1,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 2,
//                'country_id' => 11,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 3,
//                'country_id' => 11,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 4,
//                'country_id' => 15,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 5,
//                'country_id' => 15,
//                'name' => 'National Identity Card',
//                'code' => 'national_identity_card',
//                'sides' => '2',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'NI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'national_identity_card',
//                    'shuftipro_document_type' => 'id_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 6,
//                'country_id' => 15,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 7,
//                'country_id' => 17,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 8,
//                'country_id' => 17,
//                'name' => 'National Identity Card',
//                'code' => 'national_identity_card',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'NI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'national_identity_card',
//                    'shuftipro_document_type' => 'id_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 9,
//                'country_id' => 18,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 10,
//                'country_id' => 18,
//                'name' => 'National Identity Card',
//                'code' => 'national_identity_card',
//                'sides' => '2',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'NI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'national_identity_card',
//                    'shuftipro_document_type' => 'id_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 11,
//                'country_id' => 18,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 12,
//                'country_id' => 25,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 13,
//                'country_id' => 32,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 14,
//                'country_id' => 32,
//                'name' => 'National Identity Card',
//                'code' => 'national_identity_card',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'NI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'national_identity_card',
//                    'shuftipro_document_type' => 'id_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 15,
//                'country_id' => 32,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 16,
//                'country_id' => 36,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 17,
//                'country_id' => 44,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 18,
//                'country_id' => 44,
//                'name' => 'National Identity Card',
//                'code' => 'national_identity_card',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'NI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'national_identity_card',
//                    'shuftipro_document_type' => 'id_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 19,
//                'country_id' => 44,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 20,
//                'country_id' => 56,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 21,
//                'country_id' => 56,
//                'name' => 'National Identity Card',
//                'code' => 'national_identity_card',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'NI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'national_identity_card',
//                    'shuftipro_document_type' => 'id_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 22,
//                'country_id' => 56,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '2',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 23,
//                'country_id' => 56,
//                'name' => 'Residence Permit',
//                'code' => 'residence_permit',
//                'sides' => '2',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'RP',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'residence_permit',
//                    'shuftipro_document_type' => 'residence_permit',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 24,
//                'country_id' => 79,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 25,
//                'country_id' => 79,
//                'name' => 'National Identity Card',
//                'code' => 'national_identity_card',
//                'sides' => '2',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'NI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'national_identity_card',
//                    'shuftipro_document_type' => 'id_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 26,
//                'country_id' => 79,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 27,
//                'country_id' => 96,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 28,
//                'country_id' => 96,
//                'name' => 'National Identity Card',
//                'code' => 'national_identity_card',
//                'sides' => '2',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'NI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'national_identity_card',
//                    'shuftipro_document_type' => 'id_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 29,
//                'country_id' => 96,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 30,
//                'country_id' => 99,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 31,
//                'country_id' => 99,
//                'name' => 'National Identity Card',
//                'code' => 'national_identity_card',
//                'sides' => '2',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'NI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'national_identity_card',
//                    'shuftipro_document_type' => 'id_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 32,
//                'country_id' => 99,
//                'name' => 'Voter Id',
//                'code' => 'voter_id',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'VI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'voter_id',
//                    'shuftipro_document_type' => 'voter_id',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 33,
//                'country_id' => 99,
//                'name' => 'Tax Id',
//                'code' => 'tax_id',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => null,
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'tax_id',
//                    'shuftipro_document_type' => 'tax_id',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 34,
//                'country_id' => 100,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 35,
//                'country_id' => 100,
//                'name' => 'National Identity Card',
//                'code' => 'national_identity_card',
//                'sides' => '2',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'NI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'national_identity_card',
//                    'shuftipro_document_type' => 'id_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 36,
//                'country_id' => 100,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 37,
//                'country_id' => 109,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 38,
//                'country_id' => 101,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 39,
//                'country_id' => 102,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 40,
//                'country_id' => 104,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 41,
//                'country_id' => 104,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 42,
//                'country_id' => 107,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 43,
//                'country_id' => 107,
//                'name' => 'National Identity Card',
//                'code' => 'national_identity_card',
//                'sides' => '2',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'NI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'national_identity_card',
//                    'shuftipro_document_type' => 'id_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 44,
//                'country_id' => 107,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 45,
//                'country_id' => 107,
//                'name' => 'Residence Permit',
//                'code' => 'residence_permit',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'RP',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'residence_permit',
//                    'shuftipro_document_type' => 'residence_permit',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 46,
//                'country_id' => 107,
//                'name' => 'Social Security Card',
//                'code' => 'social_security_card',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'SS',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'social_security_card',
//                    'shuftipro_document_type' => 'social_security_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 47,
//                'country_id' => 107,
//                'name' => 'Postal Identity Card',
//                'code' => 'postal_identity_card',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PO',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'postal_identity_card',
//                    'shuftipro_document_type' => 'postal_identity_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 48,
//                'country_id' => 108,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 49,
//                'country_id' => 108,
//                'name' => 'National Identity Card',
//                'code' => 'national_identity_card',
//                'sides' => '2',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'NI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'national_identity_card',
//                    'shuftipro_document_type' => 'id_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 50,
//                'country_id' => 108,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 51,
//                'country_id' => 112,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 52,
//                'country_id' => 113,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 53,
//                'country_id' => 113,
//                'name' => 'National Identity Card',
//                'code' => 'national_identity_card',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'NI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'national_identity_card',
//                    'shuftipro_document_type' => 'id_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 54,
//                'country_id' => 113,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 55,
//                'country_id' => 114,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 56,
//                'country_id' => 114,
//                'name' => 'National Identity Card',
//                'code' => 'national_identity_card',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'NI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'national_identity_card',
//                    'shuftipro_document_type' => 'id_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 57,
//                'country_id' => 114,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 58,
//                'country_id' => 115,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 59,
//                'country_id' => 116,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 60,
//                'country_id' => 118,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 61,
//                'country_id' => 129,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 62,
//                'country_id' => 129,
//                'name' => 'National Identity Card',
//                'code' => 'national_identity_card',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'NI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'national_identity_card',
//                    'shuftipro_document_type' => 'id_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 63,
//                'country_id' => 129,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 64,
//                'country_id' => 129,
//                'name' => 'Residence Permit',
//                'code' => 'residence_permit',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'RP',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'residence_permit',
//                    'shuftipro_document_type' => 'residence_permit',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 65,
//                'country_id' => 146,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 66,
//                'country_id' => 130,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 67,
//                'country_id' => 142,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 68,
//                'country_id' => 142,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 69,
//                'country_id' => 149,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 70,
//                'country_id' => 161,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 71,
//                'country_id' => 161,
//                'name' => 'National Identity Card',
//                'code' => 'national_identity_card',
//                'sides' => '2',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'NI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'national_identity_card',
//                    'shuftipro_document_type' => 'id_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 72,
//                'country_id' => 161,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 73,
//                'country_id' => 161,
//                'name' => 'Residence Permit',
//                'code' => 'residence_permit',
//                'sides' => '2',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'RP',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'residence_permit',
//                    'shuftipro_document_type' => 'residence_permit',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 74,
//                'country_id' => 162,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 75,
//                'country_id' => 162,
//                'name' => 'National Identity Card',
//                'code' => 'national_identity_card',
//                'sides' => '2',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'NI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'national_identity_card',
//                    'shuftipro_document_type' => 'id_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 76,
//                'country_id' => 162,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 77,
//                'country_id' => 164,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 78,
//                'country_id' => 169,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 79,
//                'country_id' => 169,
//                'name' => 'National Identity Card',
//                'code' => 'national_identity_card',
//                'sides' => '2',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'NI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'national_identity_card',
//                    'shuftipro_document_type' => 'id_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 80,
//                'country_id' => 169,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 81,
//                'country_id' => 169,
//                'name' => 'Postal Identity Card',
//                'code' => 'postal_identity_card',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PO',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'postal_identity_card',
//                    'shuftipro_document_type' => 'postal_identity_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 82,
//                'country_id' => 169,
//                'name' => 'Professional Qualification Card',
//                'code' => 'professional_qualification_card',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => null,
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'professional_qualification_card',
//                    'shuftipro_document_type' => 'professional_qualification_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 83,
//                'country_id' => 169,
//                'name' => 'Social Security Card',
//                'code' => 'social_security_card',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'SS',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'social_security_card',
//                    'shuftipro_document_type' => 'social_security_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 84,
//                'country_id' => 169,
//                'name' => 'Voter Id',
//                'code' => 'voter_id',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'VI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'voter_id',
//                    'shuftipro_document_type' => 'voter_id',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 85,
//                'country_id' => 174,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 86,
//                'country_id' => 174,
//                'name' => 'National Identity Card',
//                'code' => 'national_identity_card',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'NI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'national_identity_card',
//                    'shuftipro_document_type' => 'id_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 87,
//                'country_id' => 174,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 88,
//                'country_id' => 174,
//                'name' => 'Residence Permit',
//                'code' => 'residence_permit',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'RP',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'residence_permit',
//                    'shuftipro_document_type' => 'residence_permit',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 89,
//                'country_id' => 187,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 90,
//                'country_id' => 187,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 91,
//                'country_id' => 187,
//                'name' => 'Residence Permit',
//                'code' => 'residence_permit',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'RP',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'residence_permit',
//                    'shuftipro_document_type' => 'residence_permit',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 92,
//                'country_id' => 192,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 93,
//                'country_id' => 192,
//                'name' => 'National Identity Card',
//                'code' => 'national_identity_card',
//                'sides' => '2',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'NI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'national_identity_card',
//                    'shuftipro_document_type' => 'id_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 94,
//                'country_id' => 192,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 95,
//                'country_id' => 192,
//                'name' => 'Work Permit',
//                'code' => 'work_permit',
//                'sides' => '2',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'WP',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'work_permit',
//                    'shuftipro_document_type' => 'work_permit',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 96,
//                'country_id' => 200,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 97,
//                'country_id' => 200,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 98,
//                'country_id' => 207,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 99,
//                'country_id' => 208,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 100,
//                'country_id' => 208,
//                'name' => 'National Identity Card',
//                'code' => 'national_identity_card',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'NI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'national_identity_card',
//                    'shuftipro_document_type' => 'id_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 101,
//                'country_id' => 208,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 102,
//                'country_id' => 208,
//                'name' => 'Residence Permit',
//                'code' => 'residence_permit',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'RP',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'residence_permit',
//                    'shuftipro_document_type' => 'residence_permit',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 103,
//                'country_id' => 209,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 104,
//                'country_id' => 211,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 105,
//                'country_id' => 211,
//                'name' => 'National Identity Card',
//                'code' => 'national_identity_card',
//                'sides' => '2',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'NI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'national_identity_card',
//                    'shuftipro_document_type' => 'id_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 106,
//                'country_id' => 211,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 107,
//                'country_id' => 212,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 108,
//                'country_id' => 219,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 109,
//                'country_id' => 224,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 110,
//                'country_id' => 224,
//                'name' => 'National Identity Card',
//                'code' => 'national_identity_card',
//                'sides' => '2',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'NI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'national_identity_card',
//                    'shuftipro_document_type' => 'id_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 111,
//                'country_id' => 224,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 112,
//                'country_id' => 224,
//                'name' => 'Residence Permit',
//                'code' => 'residence_permit',
//                'sides' => '2',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'RP',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'residence_permit',
//                    'shuftipro_document_type' => 'residence_permit',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 113,
//                'country_id' => 229,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 114,
//                'country_id' => 232,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 115,
//                'country_id' => 232,
//                'name' => 'National Identity Card',
//                'code' => 'national_identity_card',
//                'sides' => '2',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'NI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'national_identity_card',
//                    'shuftipro_document_type' => 'id_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 116,
//                'country_id' => 232,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 117,
//                'country_id' => 237,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 118,
//                'country_id' => 237,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 119,
//                'country_id' => 164,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 120,
//                'country_id' => 130,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 121,
//                'country_id' => 142,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 122,
//                'country_id' => 142,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 123,
//                'country_id' => 19,
//                'name' => 'Passport',
//                'code' => 'passport',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'PA',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'passport',
//                    'shuftipro_document_type' => 'passport',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 124,
//                'country_id' => 19,
//                'name' => 'National Identity Card',
//                'code' => 'national_identity_card',
//                'sides' => '2',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'NI',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'national_identity_card',
//                    'shuftipro_document_type' => 'id_card',
//                ),
//                'enabled' => true,
//            ),
//            array(
//                'id' => 125,
//                'country_id' => 19,
//                'name' => 'Driving Licence',
//                'code' => 'driving_licence',
//                'sides' => '1',
//                'id_doc_type_data' => array(
//                    'trans_fast_sender_id_type_id' => 'DL',
//                    'trans_fast_receiver_id_type_id' => null,
//                    'onfido_document_type' => 'driving_licence',
//                    'shuftipro_document_type' => 'driving_license',
//                ),
//                'enabled' => true,
//            ),
//        );
//    }
}
