<?php

namespace Fintech\MetaData\Seeders;

use Fintech\MetaData\Facades\MetaData;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class RelationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach ($this->data() as $relation) {
            MetaData::relation()->create($relation);
        }
    }

    private function data()
    {
        return array(
            array('id' => '1','country_id' => NULL,'name' => 'Aunt','code' => 'aunt','enabled' => '0','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2020-08-28 07:48:52','updated_at' => '2020-11-22 22:16:29','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '2','country_id' => NULL,'name' => 'Brother','code' => 'brother','enabled' => '1','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2020-08-28 07:48:52','updated_at' => '2020-11-22 22:16:54','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '3','country_id' => NULL,'name' => 'Brother In Law','code' => 'brother-in-law','enabled' => '0','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2020-08-28 07:48:52','updated_at' => '2020-09-15 16:55:56','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '4','country_id' => NULL,'name' => 'Business Associate','code' => 'business-associate','enabled' => '0','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2020-08-28 07:48:52','updated_at' => '2020-09-15 16:56:00','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '5','country_id' => NULL,'name' => 'Cousin','code' => 'cousin','enabled' => '1','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2020-08-28 07:48:52','updated_at' => '2020-11-22 22:17:19','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '6','country_id' => NULL,'name' => 'Daughter','code' => 'daughter','enabled' => '1','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2020-08-28 07:48:52','updated_at' => '2020-08-28 07:48:52','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '7','country_id' => NULL,'name' => 'Employee','code' => 'employee','enabled' => '1','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2020-08-28 07:48:52','updated_at' => '2022-01-01 13:45:21','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '8','country_id' => NULL,'name' => 'Father','code' => 'father','enabled' => '1','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2020-08-28 07:48:52','updated_at' => '2020-08-28 07:48:52','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '9','country_id' => NULL,'name' => 'Father In Law','code' => 'father-in-law','enabled' => '1','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2020-08-28 07:48:52','updated_at' => '2020-08-28 07:48:52','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '10','country_id' => NULL,'name' => 'Friend','code' => 'friend','enabled' => '1','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2020-08-28 07:48:52','updated_at' => '2020-08-28 07:48:52','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '11','country_id' => NULL,'name' => 'Grand Father','code' => 'grand-father','enabled' => '0','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2020-08-28 07:48:52','updated_at' => '2020-09-15 16:56:05','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '12','country_id' => NULL,'name' => 'Grand Mother','code' => 'grand-mother','enabled' => '0','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2020-08-28 07:48:52','updated_at' => '2020-09-15 16:56:10','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '13','country_id' => NULL,'name' => 'Husband','code' => 'husband','enabled' => '1','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2020-08-28 07:48:52','updated_at' => '2020-08-28 07:48:52','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '14','country_id' => NULL,'name' => 'Mother','code' => 'mother','enabled' => '1','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2020-08-28 07:48:52','updated_at' => '2020-08-28 07:48:52','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '15','country_id' => NULL,'name' => 'Mother In Law','code' => 'mother-in-law','enabled' => '1','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2020-08-28 07:48:52','updated_at' => '2020-08-28 07:48:52','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '16','country_id' => NULL,'name' => 'Nephew','code' => 'nephew','enabled' => '0','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2020-08-28 07:48:52','updated_at' => '2020-09-15 16:56:14','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '17','country_id' => NULL,'name' => 'Niece','code' => 'niece','enabled' => '0','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2020-08-28 07:48:52','updated_at' => '2020-09-15 16:56:18','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '18','country_id' => NULL,'name' => 'Non Related','code' => 'non-related','enabled' => '0','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2020-08-28 07:48:52','updated_at' => '2020-09-15 16:56:22','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '19','country_id' => NULL,'name' => 'Relative','code' => 'relative','enabled' => '0','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2020-08-28 07:48:52','updated_at' => '2020-09-15 16:56:26','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '20','country_id' => NULL,'name' => 'Self','code' => 'self','enabled' => '1','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2020-08-28 07:48:52','updated_at' => '2022-01-01 13:45:21','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '21','country_id' => NULL,'name' => 'Sister','code' => 'sister','enabled' => '1','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2020-08-28 07:48:52','updated_at' => '2020-08-28 07:48:52','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '22','country_id' => NULL,'name' => 'Sister In Law','code' => 'sister-in-law','enabled' => '0','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2020-08-28 07:48:52','updated_at' => '2020-09-15 16:56:31','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '23','country_id' => NULL,'name' => 'Son','code' => 'son','enabled' => '1','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2020-08-28 07:48:52','updated_at' => '2020-08-28 07:48:52','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '24','country_id' => NULL,'name' => 'Uncle','code' => 'uncle','enabled' => '0','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2020-08-28 07:48:52','updated_at' => '2020-09-15 16:56:36','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '25','country_id' => NULL,'name' => 'Wife','code' => 'wife','enabled' => '1','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2020-08-28 07:48:52','updated_at' => '2020-11-22 22:17:52','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '26','country_id' => NULL,'name' => 'Parents','code' => 'parents','enabled' => '1','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2022-01-01 13:45:21','updated_at' => '2022-01-01 13:45:21','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '27','country_id' => NULL,'name' => 'Siblings','code' => 'siblings','enabled' => '1','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2022-01-01 13:45:21','updated_at' => '2022-01-01 13:45:21','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '28','country_id' => NULL,'name' => 'Other Relatives','code' => 'other-relatives','enabled' => '1','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2022-01-01 13:45:21','updated_at' => '2022-01-01 13:45:21','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '29','country_id' => NULL,'name' => 'Vendor','code' => 'vendor','enabled' => '0','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2022-01-01 13:45:21','updated_at' => '2022-01-02 12:46:21','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '30','country_id' => NULL,'name' => 'Supplier','code' => 'supplier','enabled' => '1','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2022-01-01 13:45:21','updated_at' => '2022-01-01 13:45:21','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '31','country_id' => NULL,'name' => 'Spouse','code' => 'spouse','enabled' => '1','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2022-01-01 13:45:21','updated_at' => '2022-01-01 13:45:21','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '32','country_id' => NULL,'name' => 'Friends','code' => 'friends','enabled' => '1','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2022-01-01 13:45:21','updated_at' => '2022-01-01 13:45:21','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '33','country_id' => NULL,'name' => 'Employer','code' => 'employer','enabled' => '0','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2022-01-01 13:45:21','updated_at' => '2022-01-02 12:47:00','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '34','country_id' => NULL,'name' => 'Child','code' => 'child','enabled' => '1','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2022-01-01 13:45:21','updated_at' => '2022-01-01 13:45:21','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '35','country_id' => NULL,'name' => 'Business Partner','code' => 'business-partner','enabled' => '0','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2022-01-01 13:45:21','updated_at' => '2022-01-02 12:47:08','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '36','country_id' => NULL,'name' => 'Agent','code' => 'agent','enabled' => '0','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2022-01-01 13:45:21','updated_at' => '2022-01-02 12:47:13','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '37','country_id' => NULL,'name' => 'Creditor','code' => 'creditor','enabled' => '0','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2022-01-01 13:45:22','updated_at' => '2022-01-02 12:47:23','deleted_at' => NULL,'restored_at' => NULL),
            array('id' => '38','country_id' => NULL,'name' => 'Others','code' => 'others','enabled' => '1','relation_data' => NULL,'creator_id' => NULL,'editor_id' => NULL,'destroyer_id' => NULL,'restorer_id' => NULL,'created_at' => '2022-01-01 13:45:22','updated_at' => '2022-01-01 13:45:22','deleted_at' => NULL,'restored_at' => NULL)
        );
    }
}
