<?php

namespace Fintech\MetaData\Seeders;

use Fintech\MetaData\Facades\MetaData;
use Illuminate\Database\Seeder;

class RemittancePurposeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach ($this->data() as $remittancePurpose) {
            MetaData::remittancePurpose()->create($remittancePurpose);
        }
    }

    private function data()
    {
        return array(
            array('id' => '1', 'country_id' => NULL, 'name' => 'Build Acquisition Renovation Property', 'code' => 'build-acquisition-renovation-property', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2020-08-28 07:48:52', 'updated_at' => '2020-09-15 16:53:30', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '2', 'country_id' => NULL, 'name' => 'Business Travel', 'code' => 'business-travel', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2020-08-28 07:48:52', 'updated_at' => '2020-09-15 16:53:34', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '3', 'country_id' => NULL, 'name' => 'Buying Goods From Suppliers', 'code' => 'buying-goods-from-suppliers', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2020-08-28 07:48:52', 'updated_at' => '2020-09-15 16:53:38', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '4', 'country_id' => NULL, 'name' => 'Compensation', 'code' => 'compensation', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2020-08-28 07:48:52', 'updated_at' => '2020-09-15 16:53:44', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '5', 'country_id' => NULL, 'name' => 'Educational Expenses', 'code' => 'educational-expenses', 'enabled' => '1', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2020-08-28 07:48:52', 'updated_at' => '2022-03-22 16:29:01', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '6', 'country_id' => NULL, 'name' => 'Family Maintenance or Savings', 'code' => 'family-maintenance-or-savings', 'enabled' => '1', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2020-08-28 07:48:52', 'updated_at' => '2022-02-06 21:31:31', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '7', 'country_id' => NULL, 'name' => 'Grants And Gifts', 'code' => 'grants-and-gifts', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2020-08-28 07:48:52', 'updated_at' => '2020-09-15 16:53:47', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '8', 'country_id' => NULL, 'name' => 'Insurance Premium', 'code' => 'insurance-premium', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2020-08-28 07:48:52', 'updated_at' => '2020-09-15 16:53:51', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '9', 'country_id' => NULL, 'name' => 'Investment In Equity Shares', 'code' => 'investment-in-equity-shares', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2020-08-28 07:48:52', 'updated_at' => '2021-12-16 09:35:46', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '10', 'country_id' => NULL, 'name' => 'Investment In Real Estate', 'code' => 'investment-in-real-estate', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2020-08-28 07:48:52', 'updated_at' => '2020-09-15 16:53:59', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '11', 'country_id' => NULL, 'name' => 'Investment In Securities', 'code' => 'investment-in-securities', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2020-08-28 07:48:52', 'updated_at' => '2020-09-15 16:54:03', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '12', 'country_id' => NULL, 'name' => 'Medical Expenses', 'code' => 'medical-expenses', 'enabled' => '1', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2020-08-28 07:48:52', 'updated_at' => '2022-02-06 21:31:47', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '13', 'country_id' => NULL, 'name' => 'Pay Employee Salary', 'code' => 'pay-employee-salary', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2020-08-28 07:48:52', 'updated_at' => '2020-09-15 16:54:07', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '14', 'country_id' => NULL, 'name' => 'Payment To Foreign Worker Agency', 'code' => 'payment-to-foreign-worker-agency', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2020-08-28 07:48:52', 'updated_at' => '2020-09-15 16:54:11', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '15', 'country_id' => NULL, 'name' => 'Personal Travels Tours', 'code' => 'personal-travels-and-tours', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2020-08-28 07:48:52', 'updated_at' => '2020-09-15 16:54:15', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '16', 'country_id' => NULL, 'name' => 'Religious Festival', 'code' => 'religious-festival', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2020-08-28 07:48:52', 'updated_at' => '2020-09-15 16:54:19', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '17', 'country_id' => NULL, 'name' => 'Rental Payment', 'code' => 'rental-payment', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2020-08-28 07:48:52', 'updated_at' => '2020-09-15 16:54:23', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '18', 'country_id' => NULL, 'name' => 'Repatriation Of Business Profits', 'code' => 'repatriation-of-business-profits', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2020-08-28 07:48:52', 'updated_at' => '2020-09-15 16:54:27', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '19', 'country_id' => NULL, 'name' => 'Repayment Of Loans', 'code' => 'repayment-of-loans', 'enabled' => '1', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2020-08-28 07:48:52', 'updated_at' => '2022-02-06 21:31:39', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '20', 'country_id' => NULL, 'name' => 'Tax Payment', 'code' => 'tax-payment', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2020-08-28 07:48:53', 'updated_at' => '2020-09-15 16:54:30', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '21', 'country_id' => NULL, 'name' => 'Travel And Transportation Expenses', 'code' => 'travel-and-transportation-expenses', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2020-08-28 07:48:53', 'updated_at' => '2020-09-15 16:54:35', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '22', 'country_id' => NULL, 'name' => 'Family or Living Expense', 'code' => 'family-or-living-expense', 'enabled' => '1', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2021-12-16 09:35:43', 'updated_at' => '2022-02-06 21:31:35', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '23', 'country_id' => NULL, 'name' => 'Charity Donation', 'code' => 'charity-donation', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2021-12-16 09:35:44', 'updated_at' => '2022-03-22 16:26:38', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '24', 'country_id' => NULL, 'name' => 'Payment For Services', 'code' => 'payment-for-services', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2021-12-16 09:35:44', 'updated_at' => '2021-12-16 09:35:44', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '25', 'country_id' => NULL, 'name' => 'Travel Expenses', 'code' => 'travel-expenses', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2021-12-16 09:35:44', 'updated_at' => '2021-12-16 09:35:44', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '26', 'country_id' => NULL, 'name' => 'Personal Asset Allocation', 'code' => 'personal-asset-allocation', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2021-12-16 09:35:45', 'updated_at' => '2021-12-16 09:35:45', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '27', 'country_id' => NULL, 'name' => 'Payment For Goods', 'code' => 'payment-for-goods', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2021-12-16 09:35:45', 'updated_at' => '2021-12-16 09:35:45', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '28', 'country_id' => NULL, 'name' => 'Capital Transfer', 'code' => 'capital-transfer', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2021-12-16 09:35:45', 'updated_at' => '2021-12-16 09:35:45', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '29', 'country_id' => NULL, 'name' => 'Employee Payroll', 'code' => 'employee-payroll', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2021-12-16 09:35:46', 'updated_at' => '2021-12-16 09:35:46', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '30', 'country_id' => NULL, 'name' => 'Goods Trade', 'code' => 'goods-trade', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2021-12-16 09:35:46', 'updated_at' => '2021-12-16 09:35:46', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '31', 'country_id' => NULL, 'name' => 'Services Trade', 'code' => 'services-trade', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2021-12-16 09:35:47', 'updated_at' => '2021-12-16 09:35:47', 'deleted_at' => NULL, 'restored_at' => NULL),
            array('id' => '32', 'country_id' => NULL, 'name' => 'Return Of Export Trade', 'code' => 'return-of-export-trade', 'enabled' => '0', 'remittance_purpose_data' => NULL, 'creator_id' => NULL, 'editor_id' => NULL, 'destroyer_id' => NULL, 'restorer_id' => NULL, 'created_at' => '2021-12-16 09:35:47', 'updated_at' => '2021-12-16 09:35:47', 'deleted_at' => NULL, 'restored_at' => NULL)
        );
    }
}
