<?php

namespace Fintech\MetaData\Seeders;

use Fintech\MetaData\Facades\MetaData;
use Illuminate\Database\Seeder;

class SubRegionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach ($this->data() as $subregion) {
            MetaData::subregion()->create($subregion);
        }
    }

    private function data()
    {
        return [
            0 => [
                'id' => '1',
                'subregion_data' => [
                ],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:10:23',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => 'Northern Africa',
                'region_id' => 1,
            ],
            1 => [
                'id' => '2',
                'subregion_data' => [
                ],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:09',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => 'Middle Africa',
            ],
            2 => [
                'id' => '3',
                'subregion_data' => [
                ],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:09',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => 'Western Africa',
                'region_id' => 1,
            ],
            3 => [
                'id' => '4',
                'subregion_data' => [
                ],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:10',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => 'Eastern Africa',
                'region_id' => 1,
            ],
            4 => [
                'id' => '5',
                'subregion_data' => [
                ],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:10',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => 'Southern Africa',
                'region_id' => 1,
            ],
            5 => [
                'id' => '6',
                'subregion_data' => [
                ],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:10',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => 'Northern America',
                'region_id' => 2,
            ],
            6 => [
                'id' => '7',
                'subregion_data' => [
                ],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:10',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => 'Caribbean',
                'region_id' => 2,
            ],
            7 => [
                'id' => '8',
                'subregion_data' => [
                ],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:10',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => 'South America',
                'region_id' => 2,
            ],
            8 => [
                'id' => '9',
                'subregion_data' => [
                ],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:11',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => 'Central America',
                'region_id' => 2,
            ],
            9 => [
                'id' => '10',
                'subregion_data' => [
                ],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:11',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => 'Central Asia',
                'region_id' => 3,
            ],
            10 => [
                'id' => '11',
                'subregion_data' => [
                ],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:11',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => 'Western Asia',
                'region_id' => 3,
            ],
            11 => [
                'id' => '12',
                'subregion_data' => [
                ],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:11',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => 'Eastern Asia',
                'region_id' => 3,
            ],
            12 => [
                'id' => '13',
                'subregion_data' => [
                ],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:12',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => 'South-Eastern Asia',
                'region_id' => 3,
            ],
            13 => [
                'id' => '14',
                'subregion_data' => [
                ],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:12',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => 'Southern Asia',
                'region_id' => 3,
            ],
            14 => [
                'id' => '15',
                'subregion_data' => [
                ],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:12',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => 'Eastern Europe',
                'region_id' => 4,
            ],
            15 => [
                'id' => '16',
                'subregion_data' => [
                ],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:12',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => 'Southern Europe',
                'region_id' => 4,
            ],
            16 => [
                'id' => '17',
                'subregion_data' => [
                ],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:12',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => 'Western Europe',
                'region_id' => 4,
            ],
            17 => [
                'id' => '18',
                'subregion_data' => [
                ],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:13',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => 'Northern Europe',
                'region_id' => 4,
            ],
            18 => [
                'id' => '19',
                'subregion_data' => [
                ],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:13',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => 'Australia and New Zealand',
                'region_id' => 5,
            ],
            19 => [
                'id' => '20',
                'subregion_data' => [
                ],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:13',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => 'Melanesia',
                'region_id' => 5,
            ],
            20 => [
                'id' => '21',
                'subregion_data' => [
                ],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:13',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => 'Micronesia',
                'region_id' => 5,
            ],
            21 => [
                'id' => '22',
                'subregion_data' => [
                ],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:13',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => 'Polynesia',
                'region_id' => 5,
            ],
        ];
    }
}
