<?php

namespace Database\Seeders;

use Fintech\MetaData\Facades\MetaData;
use Illuminate\Database\Seeder;

class SubRegionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach ($this->data() as $subregion) {
            MetaData::subregion()->create($subregion);
        }
    }

    private function data()
    {
        return [
            [
                'id' => '1',
                'subregion_data' => [],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:10:23',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => [
                    'en' => 'Northern Africa',
                    'kr' => '북아프리카',
                    'pt' => 'Norte de África',
                    'nl' => 'Noord-Afrika',
                    'co' => 'Sjeverna Afrika',
                    'fa' => 'شمال آفریقا',
                    'de' => 'Nordafrika',
                    'es' => 'Norte de África',
                    'fr' => 'Afrique du Nord',
                    'ja' => '北アフリカ',
                    'it' => 'Nordafrica',
                    'zh' => '北部非洲',
                ],
            ],
            [
                'id' => '2',
                'subregion_data' => [],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:09',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => [
                    'en' => 'Middle Africa',
                    'kr' => '중앙아프리카',
                    'pt' => 'África Central',
                    'nl' => 'Centraal-Afrika',
                    'co' => 'Srednja Afrika',
                    'fa' => 'مرکز آفریقا',
                    'de' => 'Zentralafrika',
                    'es' => 'África Central',
                    'fr' => 'Afrique centrale',
                    'ja' => '中部アフリカ',
                    'it' => 'Africa centrale',
                    'zh' => '中部非洲',
                ],
            ],
            [
                'id' => '3',
                'subregion_data' => [],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:09',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => [
                    'en' => 'Western Africa',
                    'kr' => '서아프리카',
                    'pt' => 'África Ocidental',
                    'nl' => 'West-Afrika',
                    'co' => 'Zapadna Afrika',
                    'fa' => 'غرب آفریقا',
                    'de' => 'Westafrika',
                    'es' => 'África Occidental',
                    'fr' => 'Afrique de l\'Ouest',
                    'ja' => '西アフリカ',
                    'it' => 'Africa occidentale',
                    'zh' => '西非',
                ],
            ],
            [
                'id' => '4',
                'subregion_data' => [],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:10',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => [
                    'en' => 'Eastern Africa',
                    'kr' => '동아프리카',
                    'pt' => 'África Oriental',
                    'nl' => 'Oost-Afrika',
                    'co' => 'Istočna Afrika',
                    'fa' => 'شرق آفریقا',
                    'de' => 'Ostafrika',
                    'es' => 'África Oriental',
                    'fr' => 'Afrique de l\'Est',
                    'ja' => '東アフリカ',
                    'it' => 'Africa orientale',
                    'zh' => '东部非洲',
                ],
            ],
            [
                'id' => '5',
                'subregion_data' => [],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:10',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => [
                    'en' => 'Southern Africa',
                    'kr' => '남아프리카',
                    'pt' => 'África Austral',
                    'nl' => 'Zuidelijk Afrika',
                    'co' => 'Južna Afrika',
                    'fa' => 'جنوب آفریقا',
                    'de' => 'Südafrika',
                    'es' => 'África austral',
                    'fr' => 'Afrique australe',
                    'ja' => '南部アフリカ',
                    'it' => 'Africa australe',
                    'zh' => '南部非洲',
                ],
            ],
            [
                'id' => '6',
                'subregion_data' => [],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:10',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => [
                    'en' => 'Northern America',
                    'kr' => '북미',
                    'pt' => 'América Setentrional',
                    'nl' => 'Noord-Amerika',
                    'fa' => 'شمال آمریکا',
                    'de' => 'Nordamerika',
                    'es' => 'América Norteña',
                    'fr' => 'Amérique septentrionale',
                    'ja' => '北部アメリカ',
                    'it' => 'America settentrionale',
                    'zh' => '北美地區',
                ],
            ],
            [
                'id' => '7',
                'subregion_data' => [],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:10',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => [
                    'en' => 'Caribbean',
                    'kr' => '카리브',
                    'pt' => 'Caraíbas',
                    'nl' => 'Caraïben',
                    'co' => 'Karibi',
                    'fa' => 'کارائیب',
                    'de' => 'Karibik',
                    'es' => 'Caribe',
                    'fr' => 'Caraïbes',
                    'ja' => 'カリブ海地域',
                    'it' => 'Caraibi',
                    'zh' => '加勒比地区',
                ],
            ],
            [
                'id' => '8',
                'subregion_data' => [],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:10',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => [
                    'en' => 'South America',
                    'kr' => '남아메리카',
                    'pt' => 'América do Sul',
                    'nl' => 'Zuid-Amerika',
                    'co' => 'Južna Amerika',
                    'fa' => 'آمریکای جنوبی',
                    'de' => 'Südamerika',
                    'es' => 'América del Sur',
                    'fr' => 'Amérique du Sud',
                    'ja' => '南アメリカ',
                    'it' => 'America meridionale',
                    'zh' => '南美洲',
                ],
            ],
            [
                'id' => '9',
                'subregion_data' => [],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:11',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => [
                    'en' => 'Central America',
                    'kr' => '중앙아메리카',
                    'pt' => 'América Central',
                    'nl' => 'Centraal-Amerika',
                    'co' => 'Srednja Amerika',
                    'fa' => 'آمریکای مرکزی',
                    'de' => 'Zentralamerika',
                    'es' => 'América Central',
                    'fr' => 'Amérique centrale',
                    'ja' => '中央アメリカ',
                    'it' => 'America centrale',
                    'zh' => '中美洲',
                ],
            ],
            [
                'id' => '10',
                'subregion_data' => [],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:11',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => [
                    'en' => 'Central Asia',
                    'kr' => '중앙아시아',
                    'pt' => 'Ásia Central',
                    'nl' => 'Centraal-Azië',
                    'co' => 'Srednja Azija',
                    'fa' => 'آسیای میانه',
                    'de' => 'Zentralasien',
                    'es' => 'Asia Central',
                    'fr' => 'Asie centrale',
                    'ja' => '中央アジア',
                    'it' => 'Asia centrale',
                    'zh' => '中亚',
                ],
            ],
            [
                'id' => '11',
                'subregion_data' => [],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:11',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => [
                    'en' => 'Western Asia',
                    'kr' => '서아시아',
                    'pt' => 'Sudoeste Asiático',
                    'nl' => 'Zuidwest-Azië',
                    'co' => 'Jugozapadna Azija',
                    'fa' => 'غرب آسیا',
                    'de' => 'Vorderasien',
                    'es' => 'Asia Occidental',
                    'fr' => 'Asie de l\'Ouest',
                    'ja' => '西アジア',
                    'it' => 'Asia occidentale',
                    'zh' => '西亚',
                ],
            ],
            [
                'id' => '12',
                'subregion_data' => [],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:11',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => [
                    'en' => 'Eastern Asia',
                    'kr' => '동아시아',
                    'pt' => 'Ásia Oriental',
                    'nl' => 'Oost-Azië',
                    'co' => 'Istočna Azija',
                    'fa' => 'شرق آسیا',
                    'de' => 'Ostasien',
                    'es' => 'Asia Oriental',
                    'fr' => 'Asie de l\'Est',
                    'ja' => '東アジア',
                    'it' => 'Asia orientale',
                    'zh' => '東亞',
                ],
            ],
            [
                'id' => '13',
                'subregion_data' => [],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:12',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => [
                    'en' => 'South-Eastern Asia',
                    'kr' => '동남아시아',
                    'pt' => 'Sudeste Asiático',
                    'nl' => 'Zuidoost-Azië',
                    'co' => 'Jugoistočna Azija',
                    'fa' => 'جنوب شرق آسیا',
                    'de' => 'Südostasien',
                    'es' => 'Sudeste Asiático',
                    'fr' => 'Asie du Sud-Est',
                    'ja' => '東南アジア',
                    'it' => 'Sud-est asiatico',
                    'zh' => '东南亚',
                ],
            ],
            [
                'id' => '14',
                'subregion_data' => [],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:12',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => [
                    'en' => 'Southern Asia',
                    'kr' => '남아시아',
                    'pt' => 'Ásia Meridional',
                    'nl' => 'Zuid-Azië',
                    'co' => 'Južna Azija',
                    'fa' => 'جنوب آسیا',
                    'de' => 'Südasien',
                    'es' => 'Asia del Sur',
                    'fr' => 'Asie du Sud',
                    'ja' => '南アジア',
                    'it' => 'Asia meridionale',
                    'zh' => '南亚',
                ],
            ],
            [
                'id' => '15',
                'subregion_data' => [],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:12',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => [
                    'en' => 'Eastern Europe',
                    'kr' => '동유럽',
                    'pt' => 'Europa de Leste',
                    'nl' => 'Oost-Europa',
                    'co' => 'Istočna Europa',
                    'fa' => 'شرق اروپا',
                    'de' => 'Osteuropa',
                    'es' => 'Europa Oriental',
                    'fr' => 'Europe de l\'Est',
                    'ja' => '東ヨーロッパ',
                    'it' => 'Europa orientale',
                    'zh' => '东欧',
                ],
            ],
            [
                'id' => '16',
                'subregion_data' => [],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:12',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => [
                    'en' => 'Southern Europe',
                    'kr' => '남유럽',
                    'pt' => 'Europa meridional',
                    'nl' => 'Zuid-Europa',
                    'co' => 'Južna Europa',
                    'fa' => 'جنوب اروپا',
                    'de' => 'Südeuropa',
                    'es' => 'Europa del Sur',
                    'fr' => 'Europe du Sud',
                    'ja' => '南ヨーロッパ',
                    'it' => 'Europa meridionale',
                    'zh' => '南欧',
                ],
            ],
            [
                'id' => '17',
                'subregion_data' => [],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:12',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => [
                    'en' => 'Western Europe',
                    'kr' => '서유럽',
                    'pt' => 'Europa Ocidental',
                    'nl' => 'West-Europa',
                    'co' => 'Zapadna Europa',
                    'fa' => 'غرب اروپا',
                    'de' => 'Westeuropa',
                    'es' => 'Europa Occidental',
                    'fr' => 'Europe de l\'Ouest',
                    'ja' => '西ヨーロッパ',
                    'it' => 'Europa occidentale',
                    'zh' => '西欧',
                ],
            ],
            [
                'id' => '18',
                'subregion_data' => [],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:13',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => [
                    'en' => 'Northern Europe',
                    'kr' => '북유럽',
                    'pt' => 'Europa Setentrional',
                    'nl' => 'Noord-Europa',
                    'co' => 'Sjeverna Europa',
                    'fa' => 'شمال اروپا',
                    'de' => 'Nordeuropa',
                    'es' => 'Europa del Norte',
                    'fr' => 'Europe du Nord',
                    'ja' => '北ヨーロッパ',
                    'it' => 'Europa settentrionale',
                    'zh' => '北歐',
                ],
            ],
            [
                'id' => '19',
                'subregion_data' => [],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:13',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => [
                    'en' => 'Australia and New Zealand',
                    'kr' => '오스트랄라시아',
                    'pt' => 'Australásia',
                    'nl' => 'Australazië',
                    'co' => 'Australazija',
                    'fa' => 'استرالزی',
                    'de' => 'Australasien',
                    'es' => 'Australasia',
                    'fr' => 'Australasie',
                    'ja' => 'オーストララシア',
                    'it' => 'Australasia',
                    'zh' => '澳大拉西亞',
                ],
            ],
            [
                'id' => '20',
                'subregion_data' => [],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:13',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => [
                    'en' => 'Melanesia',
                    'kr' => '멜라네시아',
                    'pt' => 'Melanésia',
                    'nl' => 'Melanesië',
                    'co' => 'Melanezija',
                    'fa' => 'ملانزی',
                    'de' => 'Melanesien',
                    'es' => 'Melanesia',
                    'fr' => 'Mélanésie',
                    'ja' => 'メラネシア',
                    'it' => 'Melanesia',
                    'zh' => '美拉尼西亚',
                ],
            ],
            [
                'id' => '21',
                'subregion_data' => [],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:13',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => [
                    'en' => 'Micronesia',
                    'kr' => '미크로네시아',
                    'pt' => 'Micronésia',
                    'nl' => 'Micronesië',
                    'co' => 'Mikronezija',
                    'fa' => 'میکرونزی',
                    'de' => 'Mikronesien',
                    'es' => 'Micronesia',
                    'fr' => 'Micronésie',
                    'ja' => 'ミクロネシア',
                    'it' => 'Micronesia',
                    'zh' => '密克罗尼西亚群岛',
                ],
            ],
            [
                'id' => '22',
                'subregion_data' => [],
                'creator_id' => null,
                'editor_id' => null,
                'destroyer_id' => null,
                'restorer_id' => null,
                'created_at' => '2023-08-14 13:11:03',
                'updated_at' => '2023-08-25 02:22:13',
                'deleted_at' => null,
                'restored_at' => null,
                'name' => [
                    'en' => 'Polynesia',
                    'kr' => '폴리네시아',
                    'pt' => 'Polinésia',
                    'nl' => 'Polynesië',
                    'co' => 'Polinezija',
                    'fa' => 'پلی‌نزی',
                    'de' => 'Polynesien',
                    'es' => 'Polinesia',
                    'fr' => 'Polynésie',
                    'ja' => 'ポリネシア',
                    'it' => 'Polinesia',
                    'zh' => '玻里尼西亞',
                ],
            ],
        ];
    }
}
